/output/setRunNum %(run_num)i

/vis/disable

/output/setRecordLevel %(reclevel)i
/run/verbose 0

#/geom/building/makeBare
#/geom/building/makeVacuum
#/geom/shield/clear

%(preinit)s

/output/filename %(outfile)s
/run/initialize

/generator/module_CRY
/CRY/neutronOnly
/CRY/input returnNeutrons 1
/CRY/input returnProtons 1
/CRY/input returnGammas 1
/CRY/input returnPions 1
/CRY/input returnKaons 1
/CRY/input date 7-1-2016
/CRY/input latitude 90.0
/CRY/input altitude 0.0
/CRY/input subboxLength 5
/CRY/update

/run/beamOn %(nevents)i

