/control/saveHistory
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/detector/setShield true
#/detector/setLeadShieldThickness 50.8 mm
#/detector/setBPolyShieldThickness 600 mm
#/scint/setComposition T
/scint/setOpticalProcesses false

/output/setRecordLevel 2

/run/initialize
/hits/activate scintHitInner
/hits/activate SegmentPMT

#/vis/open OGLSXm
#/vis/open HepRepFile
/vis/viewer/set/style     wireframe
/vis/viewer/set/culling   global false
/vis/viewer/set/auxiliaryEdge 1
/vis/viewer/set/upThetaPhi 0 90
#/vis/viewer/set/viewpointThetaPhi 45 45
/vis/viewer/set/viewpointThetaPhi 90 0
/vis/drawVolume
/vis/scene/add/axes
/vis/scene/add/scale

#/vis/scene/add/trajectories
#/vis/scene/add/hits
#/vis/scene/endOfEventAction accumulate -1

/vis/disable

/output/filename ~/Analysis/ShortBaseline/CryMCData.root
#/output/setRootOutput

/CRY/toggleCryMode true
/CRY/input returnNeutrons 1
/CRY/input returnProtons 1
/CRY/input returnGammas 1
/CRY/input returnPions 1
/CRY/input returnKaons 1
/CRY/input date 7-1-2012
/CRY/input latitude 90.0
/CRY/input altitude 0.0
/CRY/input subboxLength 5
/CRY/update

/run/beamOn 1000

