/control/verbose 0
/run/verbose 1
/generator/verbose 0
/event/verbose 0
/tracking/verbose 0

/output/setRunNum 0

/output/setRecordLevel 2
#/output/primariesOnly

#/phys/enableOptical

#/geom/mode scintCell
#/geom/building/makeBare
#/geom/building/makeFluxTest
#/geom/shield/clear
/geom/shield/muveto 4 cm

/output/filename /home/mpmendenhall/Analysis/ShortBaseline/Run_0.root

/run/initialize

/vis/open OGLSXm
#/vis/disable
#/vis/ogl/set/displayListLimit 50000
/vis/viewer/set/style     wireframe
/vis/viewer/set/culling   global false
/vis/viewer/set/auxiliaryEdge 1
/vis/drawVolume

/vis/viewer/set/upThetaPhi 0 0
/vis/viewer/set/viewpointThetaPhi 90 90
/vis/viewer/zoom 15

#/vis/scene/add/axes
#/vis/scene/add/scale

/vis/scene/add/trajectories
/vis/scene/add/hits
/vis/scene/endOfEventAction accumulate -1

/generator/module_CRY
/CRY/input returnNeutrons 1
/CRY/input returnProtons 1
/CRY/input returnGammas 1
/CRY/input returnPions 1
/CRY/input returnKaons 1
/CRY/input date 11-7-2002
/CRY/input latitude 41.2
/CRY/input altitude 0
/CRY/input subboxLength 20
/CRY/update

#/generator/module_Cf252

/run/beamOn 100
