/control/saveHistory
/control/verbose 0
/run/verbose 2
/event/verbose 0
/tracking/verbose 0

/output/setRunNum 4567

/output/setRecordLevel 2

/run/initialize

/vis/open OGLSXm
/vis/viewer/set/style     wireframe
/vis/viewer/set/culling   global false
/vis/viewer/set/auxiliaryEdge 1
/vis/drawVolume

/vis/viewer/set/upThetaPhi 0 0
/vis/viewer/set/viewpointThetaPhi 90 90
/vis/viewer/zoom 2

#/vis/scene/add/axes
/vis/scene/add/scale


/vis/scene/add/trajectories
/vis/scene/add/hits
/vis/scene/endOfEventAction accumulate -1

#/vis/disable

/output/filename ~/Analysis/ShortBaseline/CryMCData.root

/generator/verbose 0
/run/verbose 0

/generator/module_CRY
/CRY/input returnNeutrons 1
/CRY/input returnProtons 1
/CRY/input returnGammas 1
/CRY/input returnPions 1
/CRY/input returnKaons 1
/CRY/input date 7-1-2012
/CRY/input latitude 90.0
/CRY/input altitude 0.0
/CRY/input subboxLength 5
/CRY/update

/run/beamOn 1

