/control/verbose 0
/run/verbose 1
/generator/verbose 0
/event/verbose 0
/tracking/verbose 0

/output/setRunNum 0
/output/setRecordLevel 2

/geom/mode sphere
/geom/sphere/radius 40 cm
/geom/sphere/nshells 40
/geom/sphere/material Polyethylene

/output/filename spheretest.root

/run/initialize

#/vis/open OGLSXm
/vis/disable
/vis/viewer/set/style     wireframe
/vis/viewer/set/culling   global false
/vis/viewer/set/auxiliaryEdge 1
/vis/drawVolume

/vis/scene/add/trajectories
/vis/scene/add/hits
/vis/scene/endOfEventAction accumulate -1

/generator/module/gun
/gun/particle neutron
/gun/energy 1 MeV
/gun/direction 0 0 1
/gun/position 0 0 0 m

/run/beamOn 10000
