# Visualization Macro (without run)
#
# Set up the visualization scheme

/detector/setShield true
/detector/setWrapGap 0
#/detector/setReflectivity 0.97
/detector/setNumberSegmentsX 5
/detector/setNumberSegmentsY 5
/detector/setScintillatorWidth 900
/detector/setScintillatorHeight 900
/detector/setScintillatorLength 1000
/detector/setSegmentBuffer 100
/detector/setPMTDiameter 35
/detector/setLeadShieldThickness 50.4
/detector/setBPolyShieldThickness 500
/detector/setLiPolyShieldThickness 100
/detector/setSurfaceFinish groundfrontpainted
#/detector/setSurfaceFinish polished
/detector/setVertical true
/detector/setAcrylThickness 6.35
/scint/setComposition T
/scint/setOpticalProcesses true
/hits/activate scintHitInner
/hits/activate SegmentPMT

/vis/open OGLIXm
#/vis/viewer/set/auxiliaryEdge 1
/vis/viewer/set/upThetaPhi 0 90
/vis/viewer/zoom 1
/vis/viewer/pan 0 1		      
/vis/viewer/set/viewpointThetaPhi 90 0
#/vis/viewer/zoom 0.8
/vis/drawVolume

/vis/scene/add/trajectories
/vis/scene/add/hits
/vis/scene/endOfEventAction accumulate -1
#
# Set up trajectory colours
/vis/modeling/trajectories/create/drawByParticleID 
/vis/modeling/trajectories/drawByParticleID-0/set neutron green
/vis/modeling/trajectories/drawByParticleID-0/set gamma white
/vis/modeling/trajectories/drawByParticleID-0/set anti_nu_e red
/vis/modeling/trajectories/drawByParticleID-0/setRGBA opticalphoton 1.0 0.5 0.0 1.0
/vis/modeling/trajectories/drawByParticleID-0/set e- yellow
/vis/modeling/trajectories/drawByParticleID-0/set e+ blue
/vis/modeling/trajectories/drawByParticleID-0/set mu- magenta
/vis/modeling/trajectories/drawByParticleID-0/set mu+ cyan
#
# Set up filters
/vis/filtering/trajectories/create/particleFilter
/vis/filtering/trajectories/particleFilter-0/add neutron
/vis/filtering/trajectories/particleFilter-0/add gamma
/vis/filtering/trajectories/particleFilter-0/add anti_nu_e
/vis/filtering/trajectories/particleFilter-0/add opticalphoton
/vis/filtering/trajectories/particleFilter-0/add e-
/vis/filtering/trajectories/particleFilter-0/add e+
/vis/filtering/trajectories/particleFilter-0/add mu-
/vis/filtering/trajectories/particleFilter-0/add mu+

/output/setRecordLevel 0
/output/setOutputDirectory ~/Analysis/ShortBaseline/MC/Data/trash/
/output/setRootOutput ~/Analysis/ShortBaseline/MC/Data/vis_cry.root

/CRY/toggleCryMode true
/CRY/input returnNeutrons 0
/CRY/input returnProtons 0
/CRY/input returnGammas 0
/CRY/input returnPions 0
/CRY/input returnKaons 0
/CRY/input date 7-1-2012
/CRY/input latitude 90.0
/CRY/input altitude 0.0
/CRY/input subboxLength 1
/CRY/input zoffset 0
/CRY/input xoffset 0
/CRY/input yoffset 0
/CRY/update

/random/setSeeds 12430 79876
/run/beamOn 1
