# Restricted Use - Property of AECL
#
# cosmicN.mac - created on 2010/11/24 by Aaron Ho
# GEANT4 - geant4.9.3.p01
#
# Macro File for Antineutrino Detector GEANT Model
#	Contains commands for initialization of cosmic neutron model
#
# Set verbosities
/control/saveHistory
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
#
# Visualization Commands
#/control/execute vis.mac
/vis/disable
#
# Set up geometric specifications

#
# Set up calibration source simulation
/generator/toggleCalibrationMode true
/generator/calibrate/setSource Cf252
/generator/calibrate/setPosition 0 0.8482 0 m
#/generator/calibrate/setPosition 0 0.022325 -0.8811 m
#/generator/calibrate/setPosition 1.2446 0.022325 0 m
#
# Set up scintillator specifications
/scint/setComposition L
#/scint/setComposition T
#/scint/setComposition H
#/scint/setComposition G
#
# Define optical processes
/scint/setOpticalProcesses true
#
# Define sensitive detectors
/hits/activate scintHitInner
/hits/activate SegmentPMT

# Define output tables for cosmic run
/output/setOutputDirectory ~/Analysis/ShortBaseline/MC/Data/
/output/setRootOutput ~/Analysis/ShortBaseline/MC/Data/MCData.root
#/output/setRootOutput

#
# Run the simulation
#/random/setSeeds 87913 81512
#/run/beamOn 1
/run/beamOn 100
#/run/beamOn 10000
#/run/beamOn 1000000
