# Restricted Use - Property of AECL
#
# cosmicMu.mac - created on 2010/11/24 by Aaron Ho
# GEANT4 - geant4.9.3.p01
#
# Macro File for Antineutrino Detector GEANT Model
#	Contains commands for initialization of cosmic muon model
#
# Set verbosities
/control/saveHistory
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
#
# Visualization Commands
/control/execute vis.mac
#/vis/disable
#
# Set up geometric specifications
/detector/setInnerTankGeometry false
/detector/setOuterTankGeometry false

#
# Set up cosmic neutron simulation
/generator/module/set cosmicMuon
#/generator/module/cosmicMuon/setTestAngle 89.99 deg
#/generator/module/cosmicMuon/setMonoEnergyFlag true
#/generator/module/cosmicMuon/setMuMonoEnergy 5.0 MeV
#/generator/module/cosmicMuon/setTargetPhysicalVolume Outer Tank
#/generator/module/cosmicMuon/setTargetPhysicalVolume Inner Tank
#/generator/module/cosmicMuon/setTargetPhysicalVolume Detector Shell
#/generator/module/cosmicMuon/setSourceSphereRadius 5.0 m
/generator/module/cosmicMuon/printParameters
#
# Set up scintillator specifications
#/scint/setComposition T
#/scint/setComposition H
#/scint/setComposition G
#
# Define optical processes
/scint/setOpticalProcesses true
#
# Define sensitive detectors
/hits/activate scintHitInner
/hits/activate SegmentPMT

#
# Define output tables for cosmic run
/output/setOutputDirectory ~/Analysis/ShortBaseline/MC/Data/
/output/setRootOutput ~/Analysis/ShortBaseline/MC/Data/MCData.root
#/output/setRootOutput
#
# Run the simulation
#/random/setSeeds 87913 81512
#/random/setSeeds 34570 56473
/run/beamOn 1
#/run/beamOn 1000
#/run/beamOn 20000
#/run/beamOn 600000
#/run/beamOn 1000000
#/run/beamOn 100000000
