# Restricted Use - Property of AECL
#
# cosmicN.mac - created on 2010/11/24 by Aaron Ho
# GEANT4 - geant4.9.3.p01
#
# Macro File for Antineutrino Detector GEANT Model
#	Contains commands for initialization of cosmic neutron model
#
# Set verbosities
/control/saveHistory
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/phys/enableOptical

#
# Visualization Commands
/vis/open OGLSQt
/run/initialize
/vis/drawVolume
#/vis/disable
#
# Set up geometric specifications

/generator/module_gps

# Define optical processes
#
# Define sensitive detectors
/hits/activate scintHitInner
/hits/activate SegmentPMT
#
# Define output tables for cosmic run
/output/filename /g/g19/classen2/Analysis/PROSPECT/Simulation/Data/electest2.root
/output/setRecordLevel 3

/vis/scene/add/trajectories
/vis/scene/add/hits
/vis/scene/endOfEventAction accumulate -1

/gps/ang/type iso
/gps/pos/type Volume
/gps/pos/shape Para
/gps/pos/centre 0 0 -50 cm
#/gps/pos/rot1 0 0 1
#/gps/pos/rot2 0 1 0
/gps/pos/halfx 50 cm
/gps/pos/halfy 50 cm
/gps/pos/halfz 50 cm
/gps/ene/mono 4.0 MeV
/gps/particle e-


# Run the simulation
/random/setSeeds 97913 11512
#/run/beamOn 1
/run/beamOn 500
#/run/beamOn 10000
#/run/beamOn 1000000



