# Restricted Use - Property of AECL
#
# cosmicN.mac - created on 2010/11/24 by Aaron Ho
# GEANT4 - geant4.9.3.p01
#
# Macro File for Antineutrino Detector GEANT Model
#	Contains commands for initialization of cosmic neutron model
#
# Set verbosities
/control/saveHistory
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
#
# Visualization Commands
#/control/execute vis.mac
/vis/disable
#
# Set up geometric specifications


# Set up scintillator specifications
#/scint/setComposition L
/scint/setComposition T
#/scint/setComposition H
#/scint/setComposition G
#
# Define optical processes
/scint/setOpticalProcesses true
#
# Define sensitive detectors
/hits/activate scintHitInner
/hits/activate SegmentPMT
#
# Define output tables for cosmic run
/output/setOutputDirectory ~/Analysis/ShortBaseline/MC/Data/
/output/setRootOutput ~/Analysis/ShortBaseline/MC/Data/MCData.root
#/output/setRootOutput

#/gun/particle e-
#/gun/energy 4 MeV

/gps/ang/type iso
/gps/pos/type Volume
/gps/pos/shape Para
/gps/pos/centre 0 550 0 cm
#/gps/pos/rot1 0 0 1
#/gps/pos/rot2 0 1 0
/gps/pos/halfx 500 cm
/gps/pos/halfy 500 cm
/gps/pos/halfz 500 cm
#/gps/pos/confine inner_box
/gps/ene/mono 4.0 MeV
/gps/particle e-


# Run the simulation
/random/setSeeds 97913 11512
#/run/beamOn 1
/run/beamOn 5
#/run/beamOn 10000
#/run/beamOn 1000000



