# Restricted Use - Property of AECL
#
# inverse.mac - created on 2010/05/21 by Aaron Ho
# GEANT4 - geant4.9.3.p01
#
# Macro File for Antineutrino GEANT Model
#	Contains commands for initialization of model
#
# Set verbosities
/control/saveHistory
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
#

# Visualization commands
#/control/execute vis.mac
/vis/disable
#
# Set up geometric specifications
/run/initialize
#
# Set up antinu simulation
/generator/module_IBD
#/generator/module/inverseBeta/setReactionVolume ScintTank_scint_box
/generator/module/inverseBeta/setFissionSpectrum true
#/generator/module/inverseBeta/setAntinuEnergy 4 MeV
#/generator/module/inverseBeta/setNeutrons false
#/generator/module/inverseBeta/setPositrons false
/generator/module/inverseBeta/setSequential true
/generator/module/inverseBeta/setFuelComposition 100 0 0 0
/generator/module/inverseBeta/printParameters
/output/setRecordLevel 3
/output/filename ~/Analysis/PROSPECT/Simulation/Data/inverseSeq.root

# Run the simulation
/run/beamOn 100000
