# Restricted Use - Property of AECL
#
# inverse.mac - created on 2010/05/21 by Aaron Ho
# GEANT4 - geant4.9.3.p01
#
# Macro File for Antineutrino GEANT Model
#	Contains commands for initialization of model
#
# Set verbosities
/control/saveHistory
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
#

# Visualization commands
#/control/execute vis.mac
/vis/disable
#
# Set up geometric specifications
/run/initialize
#
# Set up antinu simulation
/generator/module_IBD
/generator/module_IBD
#/generator/module/inverseBeta/setReactionVolume Scintillator Volume
/generator/module/inverseBeta/setFissionSpectrum false
/generator/module/inverseBeta/setAntinuEnergy 3 MeV
#/generator/module/inverseBeta/setNeutrons false
#/generator/module/inverseBeta/setPositrons false
#/generator/module/inverseBeta/setFuelComposition 55.5 5.68 44.1 1.42
/generator/module/inverseBeta/printParameters
#
# Define sensitive detectors
/hits/activate scintHitInner
/hits/activate SegmentPMT
#
# Define output tables for cosmic run
/output/setRecordLevel 3
/output/filename ~/Analysis/ShortBaseline/MC/Data/MCBetaData.root

# Run the simulation
#/random/setSeeds 34885 16395
/run/beamOn 100
#/run/beamOn 20000
#/run/beamOn 1000000
#/run/beamOn 16000000
#/run/beamOn 50000
