# Restricted Use - Property of AECL
#
# inverse.mac - created on 2010/05/21 by Aaron Ho
# GEANT4 - geant4.9.3.p01
#
# Macro File for Antineutrino GEANT Model
#	Contains commands for initialization of model
#
# Set verbosities
/control/saveHistory
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
#
# Show particle cut values
/run/particle/dumpCutValues
#
# Visualization commands
#/control/execute vis.mac
/vis/disable
#
# Set up geometric specifications
#
# Set up antinu simulation
/generator/module/set inverseBeta
/generator/module/inverseBeta/setReactionVolume Detector Shell
/generator/module/inverseBeta/setFissionSpectrum true
#/generator/module/inverseBeta/setAntinuEnergy 3 MeV
/generator/module/inverseBeta/setNeutrons false
/generator/module/inverseBeta/setPositrons true
/generator/module/inverseBeta/setFuelComposition 55.5 5.68 44.1 1.42
/generator/module/inverseBeta/printParameters
#
# Set up scintillator specifications
#/scint/setComposition S
/scint/setComposition T
#/scint/setComposition H
#
# Define optical processes
/scint/setOpticalProcesses true
#
# Define sensitive detectors
/hits/activate scintHitInner
/hits/activate SegmentPMT

#
# Define output tables for cosmic run
/output/setOutputDirectory ~/Analysis/ShortBaseline/MC/Data/
/output/setRootOutput ~/Analysis/ShortBaseline/MC/Data/MCBetaData.root

#
# Run the simulation
#/random/setSeeds 34885 16395
/run/beamOn 1000
#/run/beamOn 20000
#/run/beamOn 1000000
#/run/beamOn 16000000
#/run/beamOn 50000
